// HTML Download Functionality
// Handles generation and export of analysis results as HTML

let lastResult = null;
let sentimentData = null;
let keynessData = null;

function generateHTML(title, wordData, sentData, keynData) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
    h2 { color: #34495e; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #ecf0f1; font-weight: bold; }
    tr:hover { background-color: #f9f9f9; }
    .stat { display: inline-block; margin-right: 30px; }
    .stat-label { font-size: 0.9em; color: #7f8c8d; }
    .stat-value { font-size: 1.8em; font-weight: bold; color: #3498db; }
  </style>
</head>
<body>
  <h1>InkSight Analysis Report</h1>
  ${wordData ? `
    <h2>Word Analysis</h2>
    <div class="stat">
      <div class="stat-label">Word Count</div>
      <div class="stat-value">${wordData.word_count}</div>
    </div>
    <h3>Top Words</h3>
    <table>
      <thead>
        <tr><th>Word</th><th>Count</th></tr>
      </thead>
      <tbody>
        ${(wordData.top || []).map(w => `<tr><td>${w.w}</td><td>${w.n}</td></tr>`).join('')}
      </tbody>
    </table>
  ` : ''}
  ${sentData ? `
    <h2>Semantic Analysis</h2>
  ` : ''}
  ${keynData ? `
    <h2>Keyness Statistics</h2>
    <p><strong>Corpus:</strong> ${keynData.corpus.display_name} - ${keynData.corpus.description}</p>
    <div class="stat">
      <div class="stat-label">Total Words</div>
      <div class="stat-value">${keynData.total_words}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Unique Words</div>
      <div class="stat-value">${keynData.unique_words}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Significant Keywords</div>
      <div class="stat-value">${keynData.significant_keywords}</div>
    </div>
    <p style="background: #fef3c7; padding: 10px; border-left: 4px solid #f59e0b; color: #92400e;">
      <strong>Note:</strong> Showing top 50 most distinctive keywords. Full analysis includes ${keynData.significant_keywords} significant words.
    </p>
    <h3>Your Keywords (Over-represented in your text)</h3>
    <table>
      <thead>
        <tr><th>Word</th><th>Effect Size</th><th>Significance</th></tr>
      </thead>
      <tbody>
        ${(keynData.keywords || [])
          .filter(k => k.effect_size > 0)
          .slice(0, 25)
          .map(k => `<tr><td>${k.word}</td><td>${k.effect_size}</td><td>${k.significance}</td></tr>`)
          .join('')}
      </tbody>
    </table>
    <h3>Reference Keywords (Under-represented in your text)</h3>
    <table>
      <thead>
        <tr><th>Word</th><th>Effect Size</th><th>Significance</th></tr>
      </thead>
      <tbody>
        ${(keynData.keywords || [])
          .filter(k => k.effect_size < 0)
          .slice(0, 25)
          .map(k => `<tr><td>${k.word}</td><td>${k.effect_size}</td><td>${k.significance}</td></tr>`)
          .join('')}
      </tbody>
    </table>
  ` : ''}
  <hr>
  <p style="color: #7f8c8d; font-size: 0.9em;">Generated by InkSight on ${new Date().toLocaleString()}</p>
</body>
</html>`;
}

function downloadHTML(filename, html) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function setLastResult(data) {
  lastResult = data;
}

function setSentimentData(data) {
  sentimentData = data;
}

function setKeynessData(data) {
  keynessData = data;
}

function initDownloads(downloadBtn) {
  downloadBtn.addEventListener('click', () => {
    const html = generateHTML('InkSight Analysis Report', lastResult, sentimentData, keynessData);
    downloadHTML('inksight-analysis.html', html);
  });
}

function downloadSection(section) {
  if (section === 'word-analysis') {
    const html = generateHTML('Word Analysis', lastResult, null, null);
    downloadHTML('inksight-word-analysis.html', html);
  } else if (section === 'sentiment') {
    const html = generateHTML('Semantic Analysis', null, sentimentData, null);
    downloadHTML('inksight-semantic-analysis.html', html);
  } else if (section === 'keyness-stats') {
    const html = generateHTML('Keyness Statistics', null, null, keynessData);
    downloadHTML('inksight-keyness-stats.html', html);
  }
}

window.downloadSection = downloadSection;
window.setLastResult = setLastResult;
window.setSentimentData = setSentimentData;
window.setKeynessData = setKeynessData;
